spring.application.name=pdf_spring
spring.datasource.url= jdbc:postgresql://localhost:5432/pdf_db
spring.datasource.username= postgres
spring.datasource.password=root

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
#none, update (per versione dev), validate
spring.jpa.hibernate.ddl-auto=update

# Mostra le query SQL nei log
spring.jpa.show-sql=true

# Formatta le query SQL nei log
spring.jpa.properties.hibernate.format_sql=true


# SERVER
# porta in cui è in ascolto il backend (da cambiare se eventualmente è occupata)
server.port=8080

#Porta 4200  → Angular
#Porta 8080  → Spring Boot
#Porta 5432  → PostgreSQL